name = "blogwind"
license = "MIT"
licenselink = "https://github.com/cmlnet/blogwind/blob/master/LICENSE"
description = "blogwind, a blog theme for hugo based on TailwindCSS"
homepage = "https://github.com/cmlnet/blogwind"
tags = ["blog", "tailwindcss", "personal"]
features = ["blog"]
min_version = "0.79"

[author]
  name = "Christian Humm"
  homepage = "https://www.c-m-l.net"

[original]
  name = "Blonde"
  homepage = "https://blonde.netlify.app/"
  repo = "https://github.com/opera7133/Blonde"